Controllers/DuaController.cs
using AsthaIslamicService.CacheManager;
using AsthaIslamicService.CacheService;
using AsthaIslamicService.Models;
using AsthaIslamicService.Repository.Interfaces;
using Microsoft.AspNetCore.Mvc;
using System.Runtime.Caching.Hosting;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;
using System.Linq;

namespace AsthaIslamicService.Controllers
{
    public class DuaController : Controller
    {
        private readonly IDuaCacheManager duaCacheManager;
        private readonly IDuaService duaService;
        private readonly MemoryCacheService memoryCacheService;

        public DuaController(IDuaCacheManager duaCacheManager, IDuaService duaService)
        {
            this.duaCacheManager = duaCacheManager;
            this.duaService = duaService;
            memoryCacheService = new MemoryCacheService();
            //this.memoryCacheService = memoryCacheService;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }

        public async Task<PartialViewResult> GetDuaList()
        {
            var viewModel = new List<DuaDetailsModel>();


            if (memoryCacheService.Exists("CacheDua"))
            {
                viewModel = (List<DuaDetailsModel>)memoryCacheService.Get("CacheDua");
                ViewBag.duaList = viewModel;
            }
            else
            {

                viewModel = await duaService.GetAll();
                memoryCacheService.Set("CacheDua", viewModel);
                ViewBag.duaList = viewModel;
            }
            return PartialView("_duaPartial");
        }

        public async Task<IActionResult> Details(string id)
        {
            List<DuaDetailsModel> data = await duaService.GetAll();
            DuaDetailsModel aDua = new DuaDetailsModel();
            if (data.Count > 0)
            {
                aDua = data.FirstOrDefault(d => d.Id == id);
                ViewBag.title = aDua.Title + " |";
            }
            return View(aDua);
        }
    }
}

Controllers/LandingController.cs
using Microsoft.AspNetCore.Mvc;

namespace AsthaIslamicService.Controllers
{
    public class LandingController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Controllers/QuranController.cs
using AsthaIslamicService.CacheManager;
using AsthaIslamicService.Models;
using AsthaIslamicService.Repository.Interfaces;
using AsthaIslamicService.Repository.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace AsthaIslamicService.Controllers
{
    public class QuranController : Controller
    {
        private readonly ISurahService surahService;
        private readonly IQuranCacheManager quranCacheManager;

        public QuranController(ISurahService surahService, IQuranCacheManager quranCacheManager)
        {
            this.surahService = surahService;
            this.quranCacheManager = quranCacheManager;
        }

        public async Task<IActionResult> Index()
        {
            return View();
        }


        public async Task<IActionResult> DetailsOperation(int id, string op, string play)
        {

            List<SurahModel_Quran> aList = await quranCacheManager.GetCachedSura();

            if (op == "next")
            {
                if (id == aList.Count)
                {
                    return RedirectToAction("Details", new { id = id.ToString(), name = aList[aList.Count - 1].SuraName, num = aList[aList.Count - 1].AyatNo, play = play });
                }
                else
                {
                    return RedirectToAction("Details", new { id = (id + 1).ToString(), name = aList[id].SuraName, num = aList[id].AyatNo, play = play });
                }
            }
            if (op == "prev")
            {
                if (id == 1)
                {
                    return RedirectToAction("Details", new { id = id.ToString(), name = aList[0].SuraName, num = aList[0].AyatNo, play = play });
                }
                else
                {


                    return RedirectToAction("Details", new { id = (id - 1).ToString(), name = aList[(id - 2)].SuraName, num = aList[(id - 2)].AyatNo, play = play });
                }

            }
            return View();
        }
        public async Task<IActionResult> Details(string id, string name, string num, string play)
        {
            //List<Sura> aList = new List<Sura>();
            //Sura sura = new Sura(); 
            //sura.SuraNo = id;
            //sura.SuraName = name; 
            //sura.AyatNo = num;
            //ViewBag.suraDetail = sura;
            //ViewBag.title = name;
            //aList = await _suraService.GetById(id);
            //ViewBag.SuraList = aList;
            //ViewBag.play = play;
            ViewBag.id = id;
            ViewBag.name = name;
            ViewBag.num = num;
            ViewBag.play = play;
            return View();
        }

        public async Task<PartialViewResult> GetSuraList()
        {
            List<SurahModel_Quran> aList = await quranCacheManager.GetCachedSura();
            ViewBag.SuraList = aList;
            return PartialView("_quranPartial");
        }

        public IActionResult Test()
        {
            return View("index");
        }

        public async Task<PartialViewResult> SuraDetailData(string id, string name, string num, string play)
        {
            List<SurahModel_Quran> aList = new List<SurahModel_Quran>();
            SurahModel_Quran sura = new SurahModel_Quran();
            sura.SuraNo = id;
            sura.SuraName = name;
            sura.AyatNo = num;
            ViewBag.suraDetail = sura;
            ViewBag.title = name;
            aList = await surahService.GetById(id);
            ViewBag.SuraList = aList;
            ViewBag.play = play;
            return PartialView("_suraDetailPartialView");
        }
        //public async Task<PartialViewResult> GetSuraPartialView()
        //{
        //    var data = await quranCacheManager.GetCachedSura();
        //    return PartialView("surahPartialView", data);
        //}


        //public async Task<IActionResult> Detail(string id)
        //{

        //    var data = await quranService.GetSurah(id);
        //    return View(data);
        //}

        //public async Task<IActionResult> Next(string id)
        //{
        //    var idSplit = id.Split('-');
        //    if (!string.IsNullOrEmpty(idSplit[0]))
        //    {
        //        int iid = Convert.ToInt32(idSplit[0]);
        //        if (iid >= 114)
        //        {
        //            iid = 114;
        //            return RedirectToAction("Detail", new { id = iid.ToString() + "-bn" });
        //        }

        //        else
        //        {
        //            iid++;
        //            return RedirectToAction("Detail", new { id = iid.ToString() + "-bn" });
        //        }
        //    }


        //    return RedirectToAction("index");
        //}

        //public async Task<IActionResult> Previous(string id)
        //{
        //    var idSplit = id.Split('-');
        //    if (!string.IsNullOrEmpty(idSplit[0]))
        //    {
        //        int iid = Convert.ToInt32(idSplit[0]);
        //        if (iid <= 1)
        //        {
        //            iid = 1;
        //            return RedirectToAction("Detail", new { id = iid.ToString() + "-bn" });
        //        }

        //        else
        //        {
        //            iid = iid - 1;
        //            return RedirectToAction("Detail", new { id = iid.ToString() + "-bn" });
        //        }
        //    }


        //    return RedirectToAction("index");
        //}
    }
}

Controllers/ZakatController.cs
using AsthaIslamicService.Models;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace AsthaIslamicService.Controllers
{
    public class ZakatController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
        [HttpGet]
        public async Task<IActionResult> New()
        {


            return View();
        }

        [HttpPost]

        public ActionResult New(ZakatModel aModel)
        {
            ViewBag.ZakatRecord = aModel;
            return View();
        }

    }
}

Views/Landing/Index.cshtml
@{
    //ViewData["Title"] = "Index";
    Layout = "~/Views/Shared/_LayoutAstha.cshtml";
}
<style>
    main {
        background-color: #F8F8F8;
        height: 100%;
    }

    #topDiv {
        height: 100%;
        background-color: white;
    }

    body {
        background-color: white;
    }

    .borderBoxCard {
        width: 100%;
        background-color: #0A77B5;
        background-image: url('/images/landing/bg.svg');
        /*background: url("images/landing/bg.svg");*/
        height: 100%;
        border-radius: 12px;
        text-align: center;
        color: white;
        background-size: cover;
    }

    .mTxt {
        font-size: 16px;
        margin-top: 20px;
        font-weight: 500;
    }

    .innerRow {
        margin-right: 10px;
        margin-left: 10px;
        min-height: 30%;
    }

    .postionDiv {
        position: absolute;
        top: 50%;
        left: 50%;
        transform: translateX(-50%) translateY(-50%);
        width: 100%;
    }

    .landingicon {
        width: 80px;
    }

    @@media only screen and (max-width: 320px) {

        .mTxt {
            font-size: 14px;
        }
    }

    /*     .postionDiv {
                    position: absolute;
                    top: 20%;
                    bottom: 25%;
                    left: 25%;
                    right: 25%
                }*/

</style>
<script type="module">
    // Import the functions you need from the SDKs you need
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js";
    import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-analytics.js";
    // TODO: Add SDKs for Firebase products that you want to use
    // https://firebase.google.com/docs/web/setup#available-libraries

    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
        apiKey: "AIzaSyDtsfup4i5q0QBvjQ5fCsiTY6T0uA9Ua6M",
        authDomain: "ashtha-islamic-service.firebaseapp.com",
        projectId: "ashtha-islamic-service",
        storageBucket: "ashtha-islamic-service.appspot.com",
        messagingSenderId: "702730680243",
        appId: "1:702730680243:web:5d3b7b48ea556256a3fdc6",
        measurementId: "G-EKTHVYM075"
    };

    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    const analytics = getAnalytics(app);
</script>
@*
<nav class="navbar navbar-light" style="font-weight: 700; background: white;">
    <div class="container-fluid">
        <a class="navbar-brand" href="#">
            <img src="~/images/landing/backnavbutton.svg" alt="" width="30" height="24" class="d-inline-block align-text-top">
            আস্থা ইসলামিক
        </a>
    </div>
</nav>*@

<div class="row innerRow">
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="index" asp-controller="PrayerTime">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/payeartime.svg" />
                    <p class="mTxt">
                        নামাজের সময়
                    </p>
                </div>
            </div>
        </a>
    </div>
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="index" asp-controller="Quran">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/quran.svg" />
                    <p class="mTxt">কুরআন</p>
                </div>
            </div>
        </a>
    </div> 
</div>
<div class="row innerRow">
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="index" asp-controller="Ramadan">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/ramadan.svg" />
                    <p class="mTxt">রোজার সময়</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="index" asp-controller="Zakat">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/zakat.svg" />
                    <p class="mTxt">যাকাত</p>
                </div>
            </div>
        </a>
    </div>
</div>

<div class="row innerRow">
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="Index" asp-controller="Hadith">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/hadith.svg" />
                    <p class="mTxt">হাদিস</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="Index" asp-controller="NamesOfAllah">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/namesofallah.svg" />
                    <p class="mTxt">আল্লাহর ৯৯ টি নাম</p>
                </div>
            </div>
        </a>
    </div>
</div>

<div class="row innerRow">
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="index" asp-controller="Dua">

            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/dua.svg" />
                    <p class="mTxt">দোয়া</p>
                </div>
            </div>
        </a>
    </div>
    <div class="col-6 p-2" style="position:relative">
        <a asp-action="index" asp-controller="IslamicName">
            <div class="borderBoxCard">
                <div class="postionDiv">
                    <img class="landingicon" src="~/images/landing/islamicname.svg" />
                    <p class="mTxt">
                        ইসলামিক নাম
                    </p>
                </div>
            </div>
        </a>
    </div>
</div>
<footer class="border-top footer text-muted">
    <div class="container" style="margin: auto; width: 100%;">
        <div class="footer" style="text-align:center;">
            <img class="landingicon" src="~/images/footer/footer.svg" style="width:100%" />
        </div>
    </div>
</footer>