ViewModels/HadithViewModel.cs
namespace AsthaIslamicService.ViewModels
{
    public class HadithViewModel
    {
        public string Description { get; set; }
        public string Id { get; set; }
        public string IsFavorite { get; set; }
        public string Narrator { get; set; }
        public string Serial { get; set; }
        public string Sort { get; set; }
        public string Source { get; set; }
        public string Title { get; set; }
        public string Text { get; set; }
    }
}

Controllers/HadithController.cs
using AsthaIslamicService.CacheManager;
using AsthaIslamicService.CacheService;
using AsthaIslamicService.Repository.Interfaces;
using AsthaIslamicService.ViewModels;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace AsthaIslamicService.Controllers
{
    public class HadithController : Controller
    {
        private readonly IHadithService hadithService;
        private readonly IHadithCacheManager hadithCacheManager;

        public HadithController(IHadithService hadithService, IHadithCacheManager hadithCacheManager)
        {
            this.hadithService = hadithService;
            this.hadithCacheManager = hadithCacheManager;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public async Task<PartialViewResult> GetHadithData()
        {
            string cacheKey = CacheEnum.AllHadith;
            MemoryCacheService memoryCacheService = new MemoryCacheService();
            //CacheDataLoad _serviceCache = new CacheDataLoad();
            var subsList = new List<HadithViewModel>();
            if (memoryCacheService.Exists(cacheKey))
            {
                subsList = (List<HadithViewModel>)memoryCacheService.Get(cacheKey);
            }
            if (subsList.Count == 0)
            {
                subsList = await hadithService.GetAll();
                memoryCacheService.Set(cacheKey, subsList);
            }
            _ = Task.Run(async () =>
            {
                if (memoryCacheService.IfExpireThenSet(cacheKey))
                {
                    memoryCacheService.Set(cacheKey, await hadithService.GetAll());
                }
            });

            var data = subsList;
            ViewBag.hadithList = data;
            return PartialView("_partialHadith");
        }
    }
}

Views/Hadith/Index.cshtml
@{
    ViewData["Title"] = "হাদিস";
    Layout = "~/Views/Shared/_LayoutIslamicLife.cshtml";
}

<style>
    .surano {
        margin: auto;
        position: relative;
        top: 25%;
        color: white;
        font-size: 1rem;
    }

    .col-middle {
        margin-top: auto;
        margin-bottom: auto;
    }

    .nav-link.active {
        color: #2d99b5;
        background-color: #2d99b5;
        border-color: #dee2e6 #dee2e6 #fff;
    }

    .header-image {
        background: url('/images/hadith/hadithnumberimg.svg');
        background-position: center;
        background-size: contain;
        height: 40px;
        background-repeat: no-repeat;
        margin: auto;
        text-align: center;
    }

    a:hover {
        text-decoration: none;
        color: #129AE8;
    }

    .accordion-item {
        background-color: #fff;
    }

    .cardBoxCustom {
        /*margin-left: 10px;
        margin-right: 10px;
        margin-bottom: 10px;
        box-shadow: 0px 0px 4px #888888;*/

        margin: 2%;
        position: relative;
        top: 25%;
        color: #E0B11A;
        font-size: 1rem;
    }

    .accordion-button {
        padding: 0.5rem 1rem;
    }

        .accordion-button::after {
            margin: auto;
        }

    .accordion-flush .accordion-item {
        border-radius: 6px;
    }

        .accordion-flush .accordion-item .accordion-button {
            border-radius: 6px;
        }

    .just-line-break {
        white-space: pre-line;
    }

    main {
        background-color: rgba(248, 248, 248, 1);
    }
</style>

<script src="~/lib/jquery/dist/jquery.min.js"></script>
<script type="module">
    // Import the functions you need from the SDKs you need
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js";
    import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-analytics.js";
    // TODO: Add SDKs for Firebase products that you want to use
    // https://firebase.google.com/docs/web/setup#available-libraries

    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
        apiKey: "AIzaSyDtsfup4i5q0QBvjQ5fCsiTY6T0uA9Ua6M",
        authDomain: "ashtha-islamic-service.firebaseapp.com",
        projectId: "ashtha-islamic-service",
        storageBucket: "ashtha-islamic-service.appspot.com",
        messagingSenderId: "702730680243",
        appId: "1:702730680243:web:5d3b7b48ea556256a3fdc6",
        measurementId: "G-EKTHVYM075"
    };

    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    const analytics = getAnalytics(app);
</script>
<nav class="navbar navbar-light bg-light">
    <div class="col-1 text-end">
        <a asp-action="Index" asp-controller="Landing" class="navbar-brand ">

            <i class="fa fa-angle-left "></i>
        </a>
    </div>
    <div class="col-10 ">
        <h5 class="m-0 text-center">
            হাদিস সমূহ
        </h5>
    </div>
    <div class="col-1">
    </div>
</nav>

<div id="partialView"></div>



<script>
    $(document).ready(function () {
        LoadPartialView();
    });



    function LoadPartialView() 
    {
        $.ajax({
            type: "GET",
            async: true,
            url: "Hadith/GetHadithData",
            //url: "@Url.Action("GetHadithData", "Hadith")",
            dataType: "html",
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                $('#partialView').empty();
                $('#partialView').html(data);
            }
        });

    }
</script>

Views/Hadith/_partialHadith.cshtml
@using AsthaIslamicService.ViewModels;
@{
    var hadithList = (List<HadithViewModel>)ViewBag.hadithList;
}
@{
    int rCount = 0;
}
<script src="~/lib/jquery/dist/jquery.min.js"></script>
<div class="mt-4">
    <div class="accordion accordion-flush" id="accordionFlushExample">
        @if (hadithList.Count > 0)
        {

            foreach (var x in hadithList)
            {
                rCount = @rCount + 1;

                <div class="accordion-item cardBoxCustom accordionCL">
                    <div class="accordion-header">
                        <div class="accordion-button collapsed row px-2" data-bs-toggle="collapse" data-bs-target="#flush-@x.Id" aria-expanded="false" aria-controls="flush-@x.Id">
                            <div class="col-3 p-2">
                                <div class="header-image">
                                    <p class="surano tobng" style="color:#E0B11A">@rCount</p>

                                </div>
                            </div>
                            <div class="col-7 p-0 col-middle">
                                <div class="row py-2">

                                    <div class="col-12 padding ">@x.Title</div>
                                </div>
                            </div>
                        </div>
                    </div>
                    <div id="flush-@x.Id" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body" id="accrd_@x.Id">

                            <div style="padding:10px">
                                <div style="color:#555555">
                                    <p class="just-line-break">@x.Text</p>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }
        }



    </div>
</div>

<script>
    $('.tobng').each(function () {

        var currentElement = $(this);

        var value = currentElement.html().trim(); // if it is an input/select/textarea field
        currentElement.html(convertToBanglanumber(value));
        // TODO: do something with the value
    });



    function convertToBanglanumber(input) {

        var finalEnlishToBanglaNumber =
            { '0': '০', '1': '১', '2': '২', '3': '৩', '4': '৪', '5': '৫', '6': '৬', '7': '৭', '8': '৮', '9': '৯' };
        var retStr = input;
        for (var x in finalEnlishToBanglaNumber) {
            retStr = retStr.replace(new RegExp(x, 'g'), finalEnlishToBanglaNumber[x]);
        }


        retStr = retStr.replace("AM", "এএম");
        retStr = retStr.replace("PM", "পিএম");
        return retStr;


    }
</script>