Controllers/NamesOfAllahController.cs
using AsthaIslamicService.CacheService;
using AsthaIslamicService.Models;
using AsthaIslamicService.Repository.Interfaces;
using AsthaIslamicService.Repository.Services;
using Microsoft.AspNetCore.Mvc;
using System.Collections.Generic;
using System.Threading.Tasks;
using System;

namespace AsthaIslamicService.Controllers
{
    public class NamesOfAllahController : Controller
    {
        private readonly ITokenService tokenService;
        private readonly INameOfAllahService nameOfAllahService;

        public NamesOfAllahController(ITokenService tokenService, INameOfAllahService nameOfAllahService)
        {
            this.tokenService = tokenService;
            this.nameOfAllahService = nameOfAllahService;
        }
        public async Task<IActionResult> Index()
        {
            return View();
        }
        public async Task<IActionResult> Index2()
        {
            return View();
        }

        public async Task<PartialViewResult> GetNameofAllah()
        {
            //NameOfAllahService service = new NameOfAllahService();
            string cacheKey = CacheEnum.NameofAllah;
            MemoryCacheService memoryCache = new MemoryCacheService();
            if (memoryCache.Exists(cacheKey))
            {
                var data = (List<NameOfAllahViewModel>)memoryCache.Get(cacheKey);
                return PartialView("_partialNamesOfAllah", data);
            }
            else
            {
                var data = await nameOfAllahService.GetNames();
                memoryCache.Set(cacheKey, data);
                return PartialView("_partialNamesOfAllah", data);
            }
        }
        public async Task<PartialViewResult> GetNameofAllah2()
        {
            //NameOfAllahService service = new NameOfAllahService();
            string cacheKey = CacheEnum.NameofAllah;
            MemoryCacheService memoryCache = new MemoryCacheService();
            if (memoryCache.Exists(cacheKey))
            {
                var data = (List<NameOfAllahViewModel>)memoryCache.Get(cacheKey);
                return PartialView("_NamesOfAllah", data);
            }
            else
            {
                var data = await nameOfAllahService.GetNames();
                memoryCache.Set(cacheKey, data);
                return PartialView("_NamesOfAllah", data);
            }
        }
    }
}

Views/NamesOfAllah/Index.cshtml
@{
    ViewData["Title"] = "আল্লাহর ৯৯ নাম";
    Layout = "~/Views/Shared/_LayoutIslamicLife.cshtml";
}

<style>
    .surano {
        margin: auto;
        position: relative;
        top: 25%;
        color: #E0B11A;
        font-size: 1rem;
    }

    .col-middle {
        margin-top: auto;
        margin-bottom: auto;
    }

    .nav-link.active {
        color: #2d99b5;
        background-color: #2d99b5;
        border-color: #dee2e6 #dee2e6 #fff;
    }

    .header-image {
        background: url('/images/hadith/hadithnumberimg.svg');
        background-position: center;
        background-size: contain;
        height: 40px;
        background-repeat: no-repeat;
        margin: auto;
        text-align: center;
    }

    a:hover {
        text-decoration: none;
        color: #129AE8;
    }

    .accordion-item {
        background-color: #fff;
    }

    .cardBoxCustom {
        /*margin-left: 10px;
        margin-right: 10px;
        margin-bottom: 10px;
        box-shadow: 0px 0px 4px #888888;*/
        margin: 2%;
        position: relative;
        top: 25%;
        color: #E0B11A;
        font-size: 1rem;
    }

    .accordion-button {
        padding: 0.5rem 1rem;
    }

        .accordion-button::after {
            margin: auto;
        }

    .accordion-flush .accordion-item {
        border-radius: 6px;
    }

        .accordion-flush .accordion-item .accordion-button {
            border-radius: 6px;
        }

    .just-line-break {
        white-space: pre-line;
    }

    main {
        background-color: rgba(248, 248, 248, 1);
    }
</style>

<nav class="navbar navbar-light bg-light">
    <div class="col-1 text-end">
        <a asp-action="Index" asp-controller="Landing" class="navbar-brand ">

            <i class="fa fa-angle-left"></i>
        </a>
    </div>
    <div class="col-10 ">
        <h5 class="m-0 text-center">
            আল্লাহর ৯৯ নাম
        </h5>
    </div>
    <div class="col-1">
    </div>
</nav>


<div id="partialView"></div>

<script type="module">
    // Import the functions you need from the SDKs you need
    import { initializeApp } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-app.js";
    import { getAnalytics } from "https://www.gstatic.com/firebasejs/9.15.0/firebase-analytics.js";
    // TODO: Add SDKs for Firebase products that you want to use
    // https://firebase.google.com/docs/web/setup#available-libraries

    // Your web app's Firebase configuration
    // For Firebase JS SDK v7.20.0 and later, measurementId is optional
    const firebaseConfig = {
        apiKey: "AIzaSyDtsfup4i5q0QBvjQ5fCsiTY6T0uA9Ua6M",
        authDomain: "ashtha-islamic-service.firebaseapp.com",
        projectId: "ashtha-islamic-service",
        storageBucket: "ashtha-islamic-service.appspot.com",
        messagingSenderId: "702730680243",
        appId: "1:702730680243:web:5d3b7b48ea556256a3fdc6",
        measurementId: "G-EKTHVYM075"
    };

    // Initialize Firebase
    const app = initializeApp(firebaseConfig);
    const analytics = getAnalytics(app);
</script>
<script>

    $(document).ready(function () {
        LoadPartialView();
    });

    function LoadPartialView() {
        $.ajax({
            type: "GET",
            async: true,
            //url: "/NamesOfAllah/GetNameofAllah",
            url: "@Url.Action("GetNameofAllah", "NamesOfAllah")",
            dataType: "html",
            contentType: 'application/json; charset=utf-8',
            success: function (data) {
                $('#partialView').empty();
                $('#partialView').html(data);
            }
        });

    }
</script>

Views/NamesOfAllah/Index2.cshtml
@{
    ViewData["Title"] = "আল্লাহর ৯৯ নাম";
    Layout = "~/Views/Shared/_LayoutIslamicLife.cshtml";
}

<style>
    a {
        background: white;
        margin-top: 10px;
        width:50%;
    }

    .surano {
        margin: auto;
        position: relative;
        top: 25%;
        color: #E0B11A;
        font-size: 1rem;
    }

    .col-middle {
        margin-top: auto;
        margin-bottom: auto;
    }

    .nav-link.active {
        color: #2d99b5;
        background-color: #2d99b5;
        border-color: #dee2e6 #dee2e6 #fff;
    }

    .header-image {
        background: url('/images/hadith/hadithnumberimg.svg');
        background-position: center;
        background-size: contain;
        height: 40px;
        background-repeat: no-repeat;
        margin: auto;
        text-align: center;
    }

    a:hover {
        text-decoration: none;
        color: #129AE8;
    }

    .accordion-item {
        background-color: #fff;
    }

    .cardBoxCustom {
        margin-left: 10px;
        margin-right: 10px;
        margin-bottom: 10px;
        box-shadow: 0px 0px 4px #888888;
    }

    .accordion-button {
        padding: 0.5rem 1rem;
    }

        .accordion-button::after {
            margin: auto;
        }

    .accordion-flush .accordion-item {
        border-radius: 6px;
    }

        .accordion-flush .accordion-item .accordion-button {
            border-radius: 6px;
        }

    .just-line-break {
        white-space: pre-line;
    }

    main {
        background-color: rgba(248, 248, 248, 1);
    }

    .cstmBoxCard{
        background: #FFFFFF;
        border-radius: 4px;
    }

    .playlist {
        padding: 0px;
        margin-right: 12px;
        margin-left: 12px;
    }
</style>
<nav class="navbar navbar-light bg-light">
    <div class="col-1 text-end">
        <a asp-action="Index" asp-controller="Landing" class="navbar-brand ">

            <i class="fa fa-angle-left"></i>
        </a>
    </div>
    <div class="col-10 ">
        <h5 class="m-0 text-center">
            আল্লাহর ৯৯ নাম
        </h5>
    </div>
    <div class="col-1">
    </div>
</nav>
<div id="partialView2"></div>

@section scripts {  
    <script>

        $(document).ready(function () {
            LoadPartialView();

        });

        function LoadPartialView() {
            $.ajax({
                type: "GET",
                async: true,
                //url: "/NamesOfAllah/GetNameofAllah",
                url: "@Url.Action("GetNameofAllah2", "NamesOfAllah")",
                dataType: "html",
                contentType: 'application/json; charset=utf-8',
                success: function (data) {
                    $('#partialView2').empty();
                    $('#partialView2').html(data);
                }
            });
        }


        function play(id,element)
        {
            //currentPlayingTrack.play();
            $('#play').hide();
            $('#pause').show();
            AudioPlay(id,element);
            
        };

        function pause() {
            //currentPlayingTrack.pause();
            $('#pause').hide();
            $('#play').show();
        };




        var AudioObject = new Audio();
        function AudioPlay(id, element) {
            var elmClasslist = element.className.split(' ');
            // check div collapsed or not
            var check = elmClasslist.filter(word => word == 'collapsed');

            id = id.length == 1 ? ("0" + id + ".mp3") : (id + ".mp3");
            AudioObject.src = "https://nagad.islamicservice.net/nameAudio/" + id;

            if (check.length == 0) {
                AudioObject.play();
                $('#play').show();
            }

        }
    </script>
}

Views/NamesOfAllah/_NamesOfAllah.cshtml
@model IEnumerable<AsthaIslamicService.Models.NameOfAllahViewModel>
@{
    int rCount = 0;
}

<style>
    .header-image {
        background: url('../images/hadith/hadithnumberimg.svg');
        background-position: center;
        background-size: contain;
        height: 40px;
        background-repeat: no-repeat;
        margin: auto;
        text-align: center;
    }
</style>

<div class="playlist">
    @foreach (var item in Model)
    {
        rCount = @rCount + 1;
        <div class="row cstmBoxCard no-style mt-3">
            <div class="col-3 pt-2 pb-2">
                <div class="header-image">
                    <p class="surano tobng">@rCount</p>
                </div>
            </div>
            <div class="col-7 col-middle">
                <a asp-controller="quran" asp-action="details" asp-route-id="#" asp-route-name="#" asp-route-num="#" asp-route-play="0">
                    <div class="row">
                        <div class="col-12 padding">@item.Name (@item.Arabic)</div>
                    </div>
                </a>  
            </div>
            <div class="col-2 col-middle">
                <img id="play_@item.Id" src="~/images/quran/play.svg" value="@item.Id" onclick="play('@item.Id', this)" />
                <img id="pause_@item.Id" src="~/images/quran/stop.svg" value="@item.Id" style="display: none;" onclick="pause()" />
            </div>
        </div>      
    }
</div>
<script>
    $('.tobng').each(function () {
        var currentElement = $(this);
        var value = currentElement.html().trim(); // if it is an input/select/textarea field
        currentElement.html(convertToBanglanumber(value));

    });
</script>

Views/NamesOfAllah/_partialNamesOfAllah.cshtml
@model IEnumerable<AsthaIslamicService.Models.NameOfAllahViewModel>
@{
    int rCount = 0;
}

<div class="mt-4">
    <div class="accordion accordion-flush" id="accordionFlushExample">
        @if (Model != null)
        {
            foreach (var x in Model)
            {
                rCount = @rCount + 1;

                <div class="accordion-item cardBoxCustom accordionCL">
                    <div class="accordion-header">
                        <button class="accordion-button collapsed  px-2" data-bs-toggle="collapse" data-bs-target="#flush-@x.Id" aria-expanded="false" aria-controls="flush-@x.Id" onclick="AudioPlay('@x.Id', this)" style="height: 50px;">
                            <div class="col-3 p-2">
                                <div class="header-image">
                                    <p class="surano tobng">@rCount</p>
                                </div>
                            </div>
                            <div class="col-7 p-0 col-middle ">
                                <div class="row py-2">

                                    <div class="col-12 padding ">@x.Name</div>

                                </div>
                            </div>
                        </button>
                    </div>
                    <div id="flush-@x.Id" class="accordion-collapse collapse" data-bs-parent="#accordionFlushExample">
                        <div class="accordion-body" id="accrd_@x.Id">

                            <div style="padding:10px; padding: 10px; text-align: center; font-weight: bold; font-size: 20px">
                                <div class="row">
                                    <div class="col-12 text-center">
                                        <img class="img-fluid" src="https://nagad.islamicservice.net/img/@x.ImageUrl" />
                                    </div>


                                    <div class="row ">

                                        <div class="col-12 mt-3">

                                            <p style="color:#555555">অর্থ: @x.Meaning</p>
                                            @* <p>ফজিলত: @x.Fazilat</p>*@

                                        </div>
                                        @* <div class="col-12 mt-3">

                                <p>ফজিলত: @x.Fazilat</p>

                                </div>*@

                                    </div>

                                </div>
                            </div>
                        </div>
                    </div>
                </div>

            }
        }
    </div>
</div>



<script>
    $('.tobng').each(function () {
        var currentElement = $(this);
        var value = currentElement.html().trim(); // if it is an input/select/textarea field
        currentElement.html(convertToBanglanumber(value));

    });


    var AudioObject = new Audio();
    function AudioPlay(id, element) {
        var elmClasslist = element.className.split(' ');
        // check div collapsed or not
        var check = elmClasslist.filter(word => word == 'collapsed');

        id = id.length == 1 ? ("0" + id + ".mp3") : (id + ".mp3");
        AudioObject.src = "https://nagad.islamicservice.net/nameAudio/" + id;

        if (check.length == 0) {
            AudioObject.play();
        }
    }
</script>